# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdns < Formula
  desc "Linux DNS Management Made Simple"
  homepage "https://github.com/junevm/cdns"
  version "1.0.2"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/junevm/cdns/releases/download/v1.0.2/cdns_1.0.2_Linux_amd64.tar.gz"
    sha256 "98c9793c6b8d81e35e0ccc51345ee8711186b5736aef136127f9508a891d99ab"
    def install
      bin.install "cdns"
    end
  end
end
