# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdns < Formula
  desc "Linux DNS Management Made Simple"
  homepage "https://github.com/junevm/cdns"
  version "1.1.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/junevm/cdns/releases/download/v1.1.1/cdns_1.1.1_Linux_amd64.tar.gz"
    sha256 "3f7434223c0b79b582916dfafaf2a8cf8fb0c519804b9516b63924e98d7a1f4d"
    def install
      bin.install "cdns"
    end
  end
end
