# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdns < Formula
  desc "Linux DNS Management Made Simple"
  homepage "https://github.com/junevm/cdns"
  version "1.0.3"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/junevm/cdns/releases/download/v1.0.3/cdns_1.0.3_Linux_amd64.tar.gz"
    sha256 "a685cf01951f6c76c01c93346bd925d0c64afb9283fed081326f12644cc1dc75"
    def install
      bin.install "cdns"
    end
  end
end
