# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msifancontrol < Formula
  desc "🪭 fan control tui for msi laptops using linux"
  homepage "https://github.com/junevm/msifancontrol"
  version "1.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/junevm/msifancontrol/releases/download/v1.1.0/msifancontrol_1.1.0_Linux_amd64.tar.gz"
    sha256 "be10f9b49a13312a99c9da190c4de1f1ca545e17bdd93c5a53d631ca39e7adf8"
    def install
      bin.install "msifancontrol"
    end
  end
end
